### ISSUE TITLE
ZDF-Mediathek nicht kompatibel

### ISSUE THREAD

**Issue by wernerh2** [prof-membrane/plugin.video.zdf_de_lite#10]
Bei mir läuft Kodi 15.2 unter OpenELEC auf Raspberry Pi 2B.
Das zugehörige ZDF-Mediathek-Addon (LORE 2.2.2) wird nicht mehr aktualisiert. Es funktioniert auch nicht mehr.
Deshalb habe ich (nach Internet-Recherche) repository.membrane.zip installiert.
Nach dem Versuch, die dortige ZDF-Mediathek zu installieren wurde diese als nicht kompatibel markiert.
Nun komme ich weder vor noch zurück. Ich kann weder die alte, noch die neue ZDF-Mediathek installieren.
Mir ist aufgefallen, dass zwar LibARD installiert ist, nicht aber LibZDF.
Was kann ich tun? Wo kann ich das "nicht-kompatibel-Flag" zurück setzen?
Warum kommen eigentlich die membrane-Addons nicht in das reguläre Kodi Addon-Repository? Dann würde der Update automatisch gehen.

**Comment by prof-membrane** [comment]
15.2 ist zu alt. 

Die Add-ons kommen ins Repo, sobald sie mit den dortigen Richtlinien übereinkommen.

**Comment by wernerh2** [comment]
Naja, vom 01.03.2016. Alt? Das ist die Kodi-Version, die zu dem OpenELEC gehört. Und das wiederum ist die letzte stabile Version.
