### ISSUE TITLE
Zufällige Untertitel

### ISSUE THREAD

**Issue by timdah** [prof-membrane/plugin.video.zdf_de_lite#11]
Hallo, ich habe manchmal komplett wahllos Untertitel bei manchen Beiträgen. Ab und an hilft es einfach nochmal neu zu starten, aber meistens bleiben die bei dem ausgewählten Beitrag an.  Gibt es eine Möglichkeit das zu kontrollieren?

**Comment by prof-membrane** [comment]
Da ist bei den Kodi Einstellungen etwas falsch angewählt.

Wenn ein Video abgespielt wird:
Audio/Untertiteleinstellungen -> Untertitel aktivieren (deaktivieren) -> Als Standard für alle Medien setzen
