### ISSUE TITLE
Addon bricht mit Fehlermeldung ab

### ISSUE THREAD

**Issue by webstylr** [prof-membrane/plugin.video.zdf_de_lite#12]
**Betriebssystem:** 7.95.1 8.0, kernel: Linux ARM 32-bit version 4.9.3
**Kodi Version:** 17.0-RC3 Git:4d93228
**Add-on Version:** 3.1.2
**Bibliothek:** libZdf 1.10.5
**Bibliothek:** libMediathek3 1.3.1

Das Addon stürzt einfach ab, wenn es ausgewählt bzw gestartet wird. Dieses Verhalten ist seit gut einer Woche so. Vorher lief das Addon ohne Probleme.

Kodi log im Anhang
[kodi_log.txt](https://github.com/prof-membrane/plugin.video.zdf_de_lite/files/732330/kodi_log.txt)

**Comment by prof-membrane** [comment]
Krypton wird nicht unterstützt.
