### ISSUE TITLE
CAddonInstallJob[plugin.video.zdf_de_lite]: failed to install dependency script.module.libzdf

### ISSUE THREAD

**Issue by bequiet88** [prof-membrane/plugin.video.zdf_de_lite#13]
Hey,

gleicher Fehler, wie im ARD Issue Tracker eben schon mal submitted.

Ich will im Kodi (17.1) dein Repository per ZIP File installieren (repository.membrane.zip) und kriege im Log den Fehler der oben im Titel steht.

Meine Theorie dahinter ist, dass in "https://github.com/prof-membrane/repository.membrane/blob/master/addons.xml" in Zeile 442 noch Version 1.10.0 verlinkt ist, statt der neuen 1.10.5 von Anfang Januar 2017. Wenn das so ist, kannst du es bitte hochsetzen?

Danke und viele Grüße,
Jochen

**Comment by prof-membrane** [comment]
Im offiziellen Repo ist die ZDF Mediathek schon vorhanden, die ARD hat ein PR. Das sind angepasste Versionen für Krypton mit höheren Versionsnummern.

Ich werde in den nächsten Tagen mein Repo forken (damit Jarvis kompatible Add-ons erhalten bleiben). Danach werden alle Krypton Add-ons hochgeladen. Das dauert aber noch ein paar Tage - ich mach erstmal ne Pause.
