### ISSUE TITLE
Replace static API Token with oAuth

### ISSUE THREAD

**Issue by werty1st** [prof-membrane/plugin.video.zdf_de_lite#15]
Im Repository: https://github.com/prof-membrane/repository.membrane/tree/master/script.module.libzdf
 
wird in der Datei: script.module.libzdf-2.0.0.zip / script.module.libzdf/lib/libzdfjsonparser.py ein Authentifizierungs-Token verwendet.

Um einen eigenen Token zu erzeugen, muss unter https://developer.zdf.de/ ein Account angelegt werden.
Innerhalb dieses Accounts muss dann eine Application angelegt werden, für die dann eine Client ID und ein Client Secret erzeugt wird.

**Comment by prof-membrane** [comment]
Du kennst dich anscheinend gut aus. Bist du in irgendeiner Form für das ZDF tätig? Ich würde gerne als künftiges Team-Kodi Mitglied ein Add-on mit offiziellem "Segen" herausbringen.

Auf der verlinkten Webseite kann ich leider keinen Account erstellen. Hier wird nur ein Access Code verlangt.

**Comment by werty1st** [comment]
Hi,

ich hatte dir eine Mail an pr0lckr@googlemail.com geschrieben. Hast du die
nicht bekommen? Darin stand der Access Code für die Developer Seite.

Hast du noch eine andere Email Adresse?

Meine Adresse ist: adams.r@zdf.de

lg Ronny

**Comment by prof-membrane** [comment]
Hi. Ist es mittlerweile möglich, Zugriff auf das Developer Portal zu bekommen? Per Email konnte ich niemanden erreichen.

**Comment by werty1st** [comment]
Leider nicht. Es gibt wohl noch Klärungsbedarf bei den Nutzungsbedingungen. :(
Ich mache ein neues Ticket auf, sobald das Portal öffentlich verfügbar ist.
