### ISSUE TITLE
Videos nicht abspielbar

### ISSUE THREAD

**Issue by StarPicard** [prof-membrane/plugin.video.zdf_de_lite#16]
Hallo, ich bin mir nicht sicher ob ich verpasst habe, dass das AddOn grundlegend verändert wurde, aber bei mir gibt es seit ca. einer Woche auf mehreren Systemen Probleme mit der Wiedergabe von Videos aus der ZDF-Mediathek:

Betriebssysteme: OSMC (Pi3) / Archlinux

Kodi Version: 17.0

Add-on Version: 4.0.0
Bibliothek: libZdf (steht im Log)

- Die Videos werden unter den beiden oberen Systemen nicht mehr abgespielt.
- Alle Videos, egal aus welcher Rubrik / Untermenü

[kodi.txt](https://github.com/prof-membrane/plugin.video.zdf_de_lite/files/801019/kodi.txt)

**Comment by 42Swampy** [comment]
Hallo, gleiches Problem:

Habe libzdf 2.0.1 wieder auf 2.0.0 downgegraded.
Funktioniert jetzt erst mal wieder!

Betriebssystem: LibreElec 8.0.0 (Pi3)
Kodi Version: 17.0
Add-on Version: 4.0.0

Muß wohl ein Problem in 2.0.1 bestehen, welches vor 11 Tagen geupdated wurde.

**Comment by FoxBob79** [comment]
Hallo, gleiches Problem auch hier:

Betriebssystem: Ubuntu 16.04 mit Kodi 17.0
AddOn-version: 4.0.0
Bibliothek: 2.0.1

Nach Downgrade auf 2.0.0 läuft die Mediathek zwar wieder (DANKE für den TIP an 42Swampy) aber bei Zugriff über das Favoriten Menü führt es immer noch zum Absturz! Gehe ich direkt in das AddOn läuft es mit der libZDF_2.0.0 wieder. 

Da ich meine T95M-Box (S905X) neu aufgesetzt habe kann ich leider nicht zurück auf libZDF_2.0.0 und hänge auf 2.0.1 fest. Ob da der Downgrade funktioniert kann ich leider nicht sagen. 

Es wäre also echt nett wenn libZDF_2.0.2 veröffentlich würde und wenn es nur eine Kopie der 2.0.0 Version ist um die Mediathek wieder ans Laufen zu bekommen :-)

PS: SUPER vielen DANK für die ganze Arbeit die Du in dieses Projekt steckst!! Meine Bewunderung und Respekt gehört Dir!!

**Comment by prof-membrane** [comment]
Das ZDF ändert im Moment immer mal was an den Schnittstellen. Mit 2.0.2 nutze ich zwei verschiedene Keys. Eine dauerhafte Lösung wird es hoffentlich in Zukunft geben.

**Comment by FoxBob79** [comment]
SUPER!! Vielen vielen Dank!! :-) Gleich mal die Updates starten...

**Comment by 42Swampy** [comment]
Vielen Dank!
Ohne Deine Plugins wäre für mich KODI nur die Hälfte wert.
TOLLE Arbeit!!!
