### ISSUE TITLE
Installation schlägt fehl

### ISSUE THREAD

**Issue by d0m84** [prof-membrane/plugin.video.zdf_de_lite#17]
Hi,

ich nutze folgende Versionen:

- Openelec 7.0.1
- Kodi 16.1

Die Installation des ZDF Plugins (4.0) und des ARD Plugins (5.0) schlagen beide mit der gleichen Meldung fehl. Mit Openelec 6.0.3 ist die Installation auch nicht möglich. Den Fehler bei dieser Version hat schon ein anderer Nutzer auf Github gemeldet.

13:56:54 142.906052 T:1561093024   ERROR: CAddonInstallJob[plugin.video.zdf_de_lite]: Die Abhängigkeit auf xbmc.python in Version 2.25.0 konnte nicht aufgelöst werden.

13:57:48 196.638245 T:1765557152   ERROR: CAddonInstallJob[plugin.video.ardmediathek_de]: Die Abhängigkeit auf xbmc.python in Version 2.25.0 konnte nicht aufgelöst werden.

Da es im Moment mit openelec scheinbar überhaupt nicht funktioniert wäre es klasse wenn du dir dies einmal anschauen könntest. Danke und Grüße.

**Comment by prof-membrane** [comment]
Jarvis wird nicht unterstützt.

**Comment by d0m84** [comment]
Mit Isengard funktioniert es ja auch nicht. (Openelec 6.0.3, Kodi 15.2). Gleiche Fehlermeldung nur andere Python Versionsnummer in der Meldung.

**Comment by prof-membrane** [comment]
Isengard ist ja noch älter...

**Comment by d0m84** [comment]
Ist Openelec also generell nicht mehr supported?

**Comment by prof-membrane** [comment]
Ich supporte - wie auch im Wiki beschrieben - nur Krypton Installation auf Windows, Linux (mittels ppa) und LibreElec (letzeres incl. RPi).

Aus Zeit-/Kostengründen kann ich nicht jede Kombination aus Kodi und Plattform unterstützen. Ich besitze selbst nur Windows/LibreElec Geräte.

Sollte OE Krypton bekommen, wird das immer noch nicht von mir unterstützt, die Add-ons sollten aber trotzdem laufen. Generell würde ich den Umstieg auf dem quasi Nachfolger LibreElec empfehlen. OE ist so gut wie tot.

**Comment by d0m84** [comment]
Danke für den Tipp. Ich wusste bis jetzt nicht das es eine Spaltung der Community gab und Libreelec existiert. Habe Libreelec nun installiert und alles ist gut.
