### ISSUE TITLE
ZDF - Nach Datum - heute geht nicht

### ISSUE THREAD

**Issue by MRLB** [prof-membrane/plugin.video.zdf_de_lite#18]
Leider geht im Addon die heutigen ZDF-Sendungen nicht. Die Übersichtsseite öffnet nicht. Da ich unterwegs bin komme ich leider nicht an den Log.

Betriebssystem: Android Geräte (Tablet)

Kodi Version: 17.1

Add-on Version: 4.0.0

Bibliothek: libZdf 2.0.2

Bibliothek: libMediathek3 1.3.4

**Comment by MRLB** [comment]
Es Händeln sich dabei um Videos vom 30. April. 1. Mai geht wieder

**Comment by prof-membrane** [comment]
In meinem Repo ist es nun gefixt. Mal sehen wann ich Zeit hab, auch die Version im offiziellen Repo zu updaten.
