### ISSUE TITLE
Installiere libMediathek nicht libMediathek2 als dependency

### ISSUE THREAD

**Issue by imsodin** [prof-membrane/plugin.video.zdf_de_lite#5]
Ich habe das Addon "ZDF Mediathek" 3.0.1 vom Repo membrane 1.9.0 installiert. Das addon startet nicht und u.a. die folgende Meldung steht im Log:

    17:50:45 T:140139922564864   ERROR: EXCEPTION: Unknown addon id 'script.module.libMediathek'.

Tatsächlich war nur libMediathek2 installiert.
Als Test habe ich auch noch die Unithek installiert, wobei libMediathek installiert wurde und nun läuft alles. Es scheint also, als ob libMediathek fehlt als dependency oder fälschlicherweise libMediathek2 statt libMediathek gelistet ist.

**Comment by seuffert** [comment]
had the same issue - and installing unithek helped.

**Comment by prof-membrane** [comment]
Die libMediathek2 ist schon in Ordnung. Durch einen Fehler musste auch die libMediathek installiert sein. Das wird mit der libmediathek3 Vergangenheit sein.

**Comment by imsodin** [comment]
Mit der libMediathek2 gibts auch keine Probleme. Es gibt grundsätzlich keine Probleme mit den libs, sondern mit der Installation von der ZDF Mediathek, da dort libMediathek nicht als dependency installiert wird.
Wie ist dieses Problem nun gelöst bzw. was hat das mit libmediathek3 zu tun?
