### ISSUE TITLE
Suche funktioniert nicht

### ISSUE THREAD

**Issue by stemaj** [prof-membrane/plugin.video.zdf_de_lite#6]
Hallo,
beispielsweise ergibt die Suche nach "Wetter" eine Fehlermeldung.

Betriebssystem: LibreElec/Windows
Kodi Version: 17
Add-on Version: 3.0.1
Bibliothek: libZdf 1.0.6
Bibliothek: libMediathek2 1.1.16

Gruß,

**Comment by prof-membrane** [comment]
fixed
