### ISSUE TITLE
ZDF Mediathek Fehler

### ISSUE THREAD

**Issue by timdah** [prof-membrane/plugin.video.zdf_de_lite#7]
Betriebssystem: RetroPie, Windows, Android

Kodi Version: 16.1

Add-on Version: 3.0.1

Repository Version: 1.9.0

Ich bekomme jedes mal einen Fehler, wenn ich etwas auswähle im Addon. Ich habe es auf allen möglichen Geräten ausprobiert, aber es tritt immer der Fehler auf.

[kodi.log.txt](https://github.com/prof-membrane/plugin.video.zdf_de_lite/files/613395/kodi.log.txt)

**Comment by prof-membrane** [comment]
Das ist ein Fehler von Kodi. Probier es mal an einem PC mit Krypton, dort sollte der SSL Fehler nicht mehr auftreten.

Siehe:
http://forum.kodi.tv/showthread.php?tid=282604
https://github.com/xbmc/xbmc/pull/10108

**Comment by timdah** [comment]
Hatte jetzt nochmal Zeit mich damit zu beschäftigen. Das Problem tritt erst ab Python2.7.9 auf, weil ab da wohl SSL Zertifikate geprüft werden.

**Comment by ha-jo** [comment]
Hallo,
Am 11.12.2016 um 00:06 schrieb en00x:
> Hatte jetzt nochmal Zeit mich damit zu beschäftigen. Das Problem tritt
> erst ab Python2.7.9 auf, weil ab da wohl SSL Zertifikate geprüft werden.
> 

ich bin nicht so der Experte, habe es aber nicht geschafft, default.py
zu patchen. Patch mault an whitespaces. Ich habs dann mit
'--ignore-whitespace' versucht. Wenn ich es dann zusammenpacke und auf
den kodi Pi kopiere, meint der, das Plugin hätte nicht die richtige
Struktur. Tut mir leid, wenn ich Dir auf den Sack gehe, aber vielleicht
ist das für den Fachmann ja eine kleine Sache.

HaJo



hajo@nullo:~/Downloads/plugin.video.zdf_de_lite-master$ patch default.py
~/Downloads/9.patch
patching file default.py
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file default.py.rej
hajo@nullo:~/Downloads/plugin.video.zdf_de_lite-master$ patch
--ignore-whitespace default.py ~/Downloads/9.patch
patching file default.py
hajo@nullo:~/Downloads/plugin.video.zdf_de_lite-master$ cat default.py
# -*- coding: utf-8 -*-
import libZdf

# Workaround for SSL certificates
import requests
requests.packages.urllib3.disable_warnings()

import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context

libZdf.list()
hajo@nullo:~/Downloads/plugin.video.zdf_de_lite-master$

**Comment by prof-membrane** [comment]
Im Funk und ZDF Add-on sind nun neue Optionen, die SSL Überprüfungen ausschalten. Könnt ihr das mal testen?

Mit Krypton sollte das Problem behoben sein. Beim Release wird der Workaround wieder rausfliegen.

**Comment by ha-jo** [comment]
Hallo,

On 12/11/2016 05:43 PM, prof-membrane wrote:
> Im Funk und ZDF Add-on sind nun neue Optionen, die SSL Überprüfungen
> ausschalten. Könnt ihr das mal testen?
> 
> Mit Krypton sollte das Problem behoben sein. Beim Release wird der
> Workaround wieder rausfliegen.
> 

ich habe Dein Repository neu aus dem ZIP File installiert und bekomme
nun ZDF Mediathek in der Version 3.1.0 als 'Nicht kompatibel' angezeigt.
(Viele andere werden auch als nicht kompatibel angezeigt.) Z.B. die BR
Mediathek wird als kompatibel angezeigt und ich habe die testweise
installiert. Damit ist alles okay.

HaJo

**Comment by timdah** [comment]
Also ich habe die Option bei keiner der beiden Mediatheken . Es wird mir aber auch kein Update angezeigt und auch nach erneuter Installation bekomme ich die Einstellung nicht. Im repository ist aber doch auch gestern und heute gar nichts an Funk oder ZDF gemacht worden, wenn ich das richtig sehe? :hushed:

**Comment by prof-membrane** [comment]
Hmmm, Git hat nicht synchronisiert. Jetzt?

**Comment by timdah** [comment]
Jetzt gehts! Aber über das Repository hab ich immer noch kein Update bekommen, musste das manuell durchführen 😯

**Comment by prof-membrane** [comment]
Das liegt aber auf jeden Fall an Kodi. Andscheinend wird verhindert, dass man Repos zu oft abfragt. Ein Neustart + Aktualisierung sollte das Problem beheben.

**Comment by timdah** [comment]
Ja denke auch, das Problem trat auch nur beim Raspberry auf. Das ist eine build in Version von RetroPie, ich glaube da stimmt sowieso etwas nicht mit der Version :smile:

**Comment by ha-jo** [comment]
Hallo,

On 12/13/2016 06:39 PM, en00x wrote:
> Jetzt gehts! Aber über das Repository hab ich immer noch kein Update
> bekommen, musste das manuell durchführen 😯
> 

ich habe es immer noch nicht hinbekommen. Ich habe
'plugin.video.zdf_de_lite-master.zip' aus dem git heruntergeladen. Darin
war nur die ungepatchte Version von default.py. Daraufhin habe ich mir
die gepatchte default.py nachgeladen und in das ZIP File eingebaut. Wenn
ich jetzt 'Addon aus Zip Datei installieren' wähle und dann die
modifizierte ZIP Datei hinwerfe, bekomme ich die Meldung: 'ZDF
Mediathek: Abhängigkeiten nicht erfüllt. Bitte den AddIn Autor
kontaktieren.'

Was fehlt mir denn da? Ich habe den Pi bereits neu gestartet. Es ändert
sich aber nichts.

HJH.

**Comment by ha-jo** [comment]
Hallo,

On 12/13/2016 06:39 PM, en00x wrote:
> Jetzt gehts! Aber über das Repository hab ich immer noch kein Update
> bekommen, musste das manuell durchführen 😯
> 

Ich habe jetzt das Debugging eingeschaltet und bekomme damit die
Information, daß mir 'script.module.libZdf' fehlt. Ich habe bereits
erfolglos danach gesucht. Woher bekomme ich die denn?


11:39:35 283.004974 T:1967341568   DEBUG: ------ Window Deinit
(FileBrowser.xml) ------
11:39:35 283.014618 T:1967341568   DEBUG: GetZipList - Processing
zip://%2fstorage%2fdownloads%2fplugin.video.zdf_de_lite-master.zip/
11:39:35 283.057770 T:1697174592   DEBUG:
CAddonInstallJob[plugin.video.zdf_de_lite]: requires
script.module.libZdf version 1.0.0 which is not available
11:39:35 283.065033 T:1697174592   ERROR:
CAddonInstallJob[plugin.video.zdf_de_lite]: dependency check failed


HJH.

**Comment by en00x** [comment]
Hi,
die default.py wurde auch nicht verändert von membrane. Am einfachsten ist es die dateien einfach zu ersetzen, also einfach die zip's entpacken und die entsprechenden plugin ordner überschreiben. Das musst du bei zdf_lite und libmediathek3 machen. Wenn dir die libZdf fehlt kannst du die auch einfach noch rein packen...

Ah und unzip meldet bei mir am raspberry korrupte zip's, über filezilla ist es aber vielleicht eh einfacher die entpackten sachen rüber zu ziehen.

**Comment by ha-jo** [comment]
Hallo
Am 14.12.2016 15:30, schrieb en00x:
> Hi,
> die default.py wurde auch nicht verändert von membrane. Am
> einfachsten ist es die dateien einfach zu ersetzen, also einfach die
> zip's entpacken und die entsprechenden plugin ordner überschreiben.
> Das musst du bei zdf_lite und libmediathek3 machen. Wenn dir die
> libZdf fehlt kannst du die auch einfach noch rein packen...
> 
> Ah und unzip meldet bei mir am raspberry korrupte zip's, über
> filezilla ist es aber vielleicht eh einfacher die entpackten sachen
> rüber zu ziehen.
> 

unzip funktioniert bei mir wohl. In dem zdf Mediathek Verzeichnis ist 
(hoffentlich= die richtige defazlt.py. libmediathek3 finde ich auf dem 
Pi aber nicht. Wenn ich die kodi.log richtig interpretiere, meckert er 
aber an python rum. Python sieht mir aber gut aus. Ich bin etwas ratlos 
im Moment. In meiner Pluginliste taucht jedenfalls die ZDF Mediathek als 
upgradeale auf. Wenn ich dann 'upgrade' klicke, sagt er, die 
Abhängigkeiten sein nicht erfüllt.


OpenELEC:~ # python -V
Python 2.7.3
OpenELEC:~ # ls -l /storage/.kodi/addons/ | grep -i zdf
drwxr-xr-x    2 root     root          4096 Dec 14 11:50 
plugin.video.zdf_de_lite-master
drwxr-xr-x    3 root     root          4096 Dec 14 11:50 
script.module.libZdf-master
OpenELEC:~ # ls -l /storage/.kodi/addons/ | grep -i mediath
drwxr-xr-x    3 root     root          4096 Dec  4 16:08 
plugin.video.ardmediathek_de
drwxr-xr-x    3 root     root          4096 Dec 11 12:56 
plugin.video.brmediathek
drwxr-xr-x    4 root     root          4096 Aug 27 19:43 
plugin.video.mediathek
drwxr-xr-x    4 root     root          4096 Dec  4 16:08 
script.module.libMediathek
drwxr-xr-x    4 root     root          4096 Dec 14 11:50 
script.module.libMediathek2
OpenELEC:~ # ls -l .kodi/addons/plugin.video.zdf_de_lite-master
total 184
-rw-r--r--    1 root     root         18092 Dec 14 11:50 LICENSE.txt
-rw-r--r--    1 root     root           682 Dec 14 14:24 addon.xml
-rw-r--r--    1 root     root            17 Dec 14 11:50 changelog.txt
-rw-r--r--    1 root     root            52 Dec 14 11:50 default.backup
-rw-r--r--    1 root     root           490 Dec 14 11:50 default.py
-rw-r--r--    1 root     root        101345 Dec 14 11:50 fanart.jpg
-rw-r--r--    1 root     root         47601 Dec 14 11:50 icon.png
OpenELEC:~ #


Grüße
HJH.

**Comment by en00x** [comment]
Okay, dann füg die libmediathek3, oder kann auch lib3mediathek sein (bin mir nicht ganz sicher :smile:), einfach auch noch manuell in den addon ordner

**Comment by prof-membrane** [comment]
Könnt ihr beiden das nicht irgendwo anders diskutieren? Das Thema hat überhaupt nichts mit diesem Ticket zu tun. Außerdem hab ich ha-jo schon in einem anderen Issue kommuniziert, dass seine Distro total veraltet ist und von mir nicht supported werden kann. Das Add-on funktioniert auf allen aktuellen Geräten.

Tauscht am besten eure Kontaktdaten aus, falls ihr das klären wollt. Am Sonntag werde ich den Offtopic löschen, damit der Tracker sauber bleibt.

**Comment by ha-jo** [comment]
Hallo,

On 12/15/2016 02:23 AM, prof-membrane wrote:
> Könnt ihr beiden das nicht irgendwo anders diskutieren? Das Thema hat
> überhaupt nichts mit diesem Ticket zu tun. Außerdem hab ich ha-jo schon
> in einem anderen Issue kommuniziert, dass seine Distro total veraltet
> ist und von mir nicht supported werden kann. Das Add-on funktioniert auf
> allen aktuellen Geräten.
> 
> Tauscht am besten eure Kontaktdaten aus, falls ihr das klären wollt. Am
> Sonntag werde ich den Offtopic löschen, damit der Tracker sauber bleibt.
> 

Ich setze Openelec in der stabilen Version ein. Die ist vom März 2016
und es ist die aktuelle Version. Von veraltet kann also keine Rede sein.
HJH.

**Comment by prof-membrane** [comment]
Kodi 15 und aktuell? Wirklich? Im Wiki steht ausführlich, dass hier nur Javis unterstützt wird. OE war schon März veraltet - 16.0 kam im Februar heraus.

Letzte Warnung, danach wird gelöscht.
