### ISSUE TITLE
unmet dependencies

### ISSUE THREAD

**Issue by ha-jo** [prof-membrane/plugin.video.zdf_de_lite#8]
Hallo,
nachdem die ZDF Mediathek scheinbar von dem alten Author nicht mehr gepflegt wird, habe ich im IRC Chat den Hinweis auf Dein Repository bekommen. Daraufhin habe ich versuchet, Dein ZDF Plugin zu installieren. Dabei kommt die Fehlermeldung: 'Abhängigkeiten nicht erfüllt. Bitte den Addon-Autor kontaktieren.' , was ich hiermit mache. Ich kann nicht sehen, welche Abhängigkeiten unerfüllt sind. Bei mir läuft Kodi in der stabilen Version vom März 2016 auf einem Raspberry Pi der ersten Generation.
Liebe Grüße
Ha-Jo

**Comment by prof-membrane** [comment]
https://github.com/prof-membrane/repository.membrane/wiki/Wie-Bugs-und-Featurerequests-zu-%C3%BCbermitteln-sind

**Comment by ha-jo** [comment]
Ich habe 
OpenELEC (official) - Version: 6.0.3, kernel: Linux ARM 32-bit version 4.1.18
installiert.  Darin ist Kodi 15.2 Git:02e7013 enthalten. Damit falle ich wohl aus Deinem Aufmerksamkeitsradius. V6.0.3 ist aber gerade die stabile Openelec Version und ich habe keine Lust, Frickelsoftware einzusetzen. Ich sehe keinen Ausweg aus der Zwickmühle und ziehe die Frage zurück.
FTU 
Ha-Jo
